services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - "build:/app/_build"
      - "deps:/app/deps"
      - "node-modules:/app/assets/node_modules"
    ports:
      - "4000:4000"
    command: mix do setup, phx.server
    environment:
      - MIX_ENV=dev

  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - "build:/app/_build"
      - "deps:/app/deps"
      - "node-modules:/app/assets/node_modules"
    command: mix do deps.get --only test, format --check-formatted, test --trace --color, credo --strict, dialyzer
    environment:
      - MIX_ENV=test

volumes:
  build:
  deps:
  node-modules:
